### ISSUE TITLE
Levelboard ranking breaks on OOB 14 

### ISSUE THREAD

**Issue by William-Carter** [Em0nky/PortalBot#37]
After the 44 way tie, the rankings seem to break down entirely.
It seems rows are sorted by points awarded, but the points awarded are incorrect i.e Inlandempirecuber gets 0.18 for 19.845, whereas nan0 gets 0.08 for 17.685.

Also I think the minimum points value should be 1, based on the formula I was shown.

After checking the second most popular IL board (08 inbounds) I was unable to replicate the issue there, however that board conveniently has exactly 1 run fewer than the 44 way tie, making it impossible to tell if the bug is due to the number of runs submitted or the large number of tied runs.

![unknown](https://user-images.githubusercontent.com/38170230/164702215-c094741a-6452-44b1-8cbc-6298a2bf24fe.png)

**Comment by Em0nky** [comment]
I'm considering using a different formula for calculating points right now which might solve this issue, use cleaner whole numbers instead of floats, and allow 100 people to get points for an IL. (Basically just 101 - the run's place which makes it a linear allocation of points). I'm also open to other ideas for formulas as well tho as people don't seem to like having a straight linear (i.e. not rewarding having higher placed times) but I also don't like how weighted the current formula is to top times.
